/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#f9f9f7',
        'surface-dim': '#dadad8',
        'surface-bright': '#f9f9f7',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f4f2',
        'surface-container': '#eeeeec',
        'surface-container-high': '#e8e8e6',
        'surface-container-highest': '#e2e3e1',
        'on-surface': '#1a1c1b',
        'on-surface-variant': '#46464b',
        'inverse-surface': '#2f3130',
        'inverse-on-surface': '#f1f1ef',
        'outline': '#76777b',
        'outline-variant': '#c7c6cb',
        'surface-tint': '#5e5e62',
        'primary': '#000000',
        'on-primary': '#ffffff',
        'primary-container': '#1b1b1f',
        'on-primary-container': '#848387',
        'inverse-primary': '#c7c6ca',
        'secondary': '#775a19',
        'on-secondary': '#ffffff',
        'secondary-container': '#fed488',
        'on-secondary-container': '#785a1a',
        'tertiary': '#000000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#191c20',
        'on-tertiary-container': '#82848a',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e3e2e6',
        'primary-fixed-dim': '#c7c6ca',
        'on-primary-fixed': '#1b1b1f',
        'on-primary-fixed-variant': '#46464a',
        'secondary-fixed': '#ffdea5',
        'secondary-fixed-dim': '#e9c176',
        'on-secondary-fixed': '#261900',
        'on-secondary-fixed-variant': '#5d4201',
        'tertiary-fixed': '#e1e2e9',
        'tertiary-fixed-dim': '#c5c6cd',
        'on-tertiary-fixed': '#191c20',
        'on-tertiary-fixed-variant': '#44474c',
        'background': '#f9f9f7',
        'on-background': '#1a1c1b',
        'surface-variant': '#e2e3e1',
      },
      fontFamily: {
        'display-hero': ['Playfair Display', 'serif'],
        'headline-xl': ['Playfair Display', 'serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'headline-sm': ['Playfair Display', 'serif'],
        'title-editorial': ['Playfair Display', 'serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'sans': ['Plus Jakarta Sans', 'sans-serif'],
        'serif': ['Playfair Display', 'serif'],
      },
      fontSize: {
        'display-hero': ['5.5rem', { lineHeight: '6rem', letterSpacing: '-0.03em', fontWeight: '400' }],
        'display-hero-mobile': ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-xl': ['3.75rem', { lineHeight: '4.25rem', letterSpacing: '-0.025em', fontWeight: '400' }],
        'headline-xl-mobile': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.015em', fontWeight: '400' }],
        'headline-lg': ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.02em', fontWeight: '400' }],
        'headline-lg-mobile': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-md': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em', fontWeight: '500' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '0em', fontWeight: '500' }],
        'title-editorial': ['1rem', { lineHeight: '1.5rem', letterSpacing: '0.05em', fontWeight: '400' }],
        'body-lg': ['1.125rem', { lineHeight: '1.875rem', letterSpacing: '-0.01em', fontWeight: '300' }],
        'body-md': ['0.9375rem', { lineHeight: '1.625rem', letterSpacing: '0em', fontWeight: '400' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.375rem', letterSpacing: '0.01em', fontWeight: '400' }],
        'label-caps': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.18em', fontWeight: '600' }],
        'label-sm': ['0.75rem', { lineHeight: '1.125rem', letterSpacing: '0.04em', fontWeight: '500' }],
      },
      spacing: {
        'gutter': '1.5rem',
        'gutter-tablet': '2rem',
        'gutter-desktop': '3rem',
        'margin': '1.25rem',
        'margin-tablet': '3rem',
        'margin-desktop': '5rem',
        'space-xs': '0.375rem',
        'space-sm': '0.75rem',
        'space-md': '1.5rem',
        'space-lg': '2.5rem',
        'space-xl': '4.5rem',
        'space-2xl': '8rem',
      },
      borderRadius: {
        'none': '0px',
        'sm': '0px',
        DEFAULT: '0px',
        'md': '0px',
        'lg': '0px',
        'xl': '0px',
        '2xl': '0px',
        '3xl': '0px',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}
